version: '2'

services:
  hrnet:
    image: hrnet
    build: .
    container_name: hrnet
    runtime: nvidia
    # command: bash -c "source /ros/src/devel/setup.bash; roslaunch hrnet.launch"
    tty: true
    volumes:
      - ./deep-high-resolution-net/models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth:/ros/src/hrnet_pose/deep-high-resolution-net/models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: "host"